### ISSUE TITLE
Design UI with usage scheme

### ISSUE THREAD

**Issue by AndrzejKrzywda00** [kristopalka/mobile-palete-picker#1]

**Comment by kristopalka** [comment]
UI zaprojektowane
![image](https://user-images.githubusercontent.com/38299425/201758071-74ef60e5-695c-4063-bc9a-88fa86deb4fe.png)

**Comment by kristopalka** [comment]
trzeba jeszcze zrobić schemat użycia, schemat strukturalny, schemat użycia komponentów
